name: Dependabot
on:
  push:
    branches: [ main ]
version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "weekly"

